display_name: Notes
packager: Amphi
packagerEmail: support@amphi.site
url: https://amphi.site
license: GPLv3

icon: assets/logo/icon_512x512.png

requires:
  - libfuse2
  - libmpv-dev
  - mpv
  - libmimalloc-dev
  - libmimalloc2.0
  - sqlite-libs

keywords:
  - Notes

generic_name: Note Taking Application
summary: Note Taking Application
group: Applications/Utilities

categories:
  - Utility
  - Productivity

startup_notify: false